version: '3.8'

services:

  db:
    image: docker.io/postgres:12
    container_name: mlflow_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=default
    ports:
      - "5432:5432"
    networks:
      - backend

  minio:
    image: docker.io/minio/minio:RELEASE.2024-08-03T04-33-23Z-cpuv1
    container_name: mlflow_artefact_store
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=jared
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DEFAULT_BUCKETS=test_bucket_1
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      - backend
    command: server /data --console-address ":9001"

  mlflow:
    build: 
      dockerfile: ./mlflow.Dockerfile
    container_name: mlflow_server
    networks:
      - frontend
      - backend
    environment:
      - MLFLOW_TRACKING_URI=postgresql+psycopg2://postgres:postgres@db:5432/default
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
      - AWS_ACCESS_KEY_ID=jared
      - AWS_SECRET_ACCESS_KEY=password
    command: mlflow server --backend-store-uri postgresql+psycopg2://postgres:postgres@db:5432/default --default-artifact-root s3://test_bucket_1 --host 0.0.0.0 --port 5000
    ports:
      - "5000:5000"

volumes:
  postgres_data:
    driver: local
  minio_data:
    driver: local

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
